SELECT * FROM REGIONS;

SELECT FIRST_NAME, LAST_NAME DEPARTMENT_ID, SALARY FROM EMPLOYEES;

SELECT EMPLOYEE_ID, EMAIL, HIRE_DATE-7 AS one_week_before_hire  FROM EMPLOYEES;

SELECT FIRST_NAME || ' ' || LAST_NAME || ' ' || JOB_ID AS our_employees FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME  FROM EMPLOYEES;

SELECT JOB_TITLE, 'min  = ' || MIN_SALARY || ' , ' || 'max = ' || MAX_SALARY AS info FROM JOBS;