
-- DESTINCT получить уникальные значения


SELECT SALARY FROM EMPLOYEES;

SELECT SALARY*1.20 FROM EMPLOYEES;

SELECT SALARY*1.20+EMPLOYEE_ID FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY,  SALARY*1.2 FROM EMPLOYEES;

SELECT  SALARY, SALARY*5/5/10-5 FROM EMPLOYEES;

SELECT COMMISSION_PCT, COMMISSION_PCT/2 FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL ;

SELECT * FROM JOB_HISTORY;

SELECT START_DATE, END_DATE FROM JOB_HISTORY;

SELECT START_DATE, END_DATE, (((END_DATE-START_DATE)+1)/30)/12 FROM JOB_HISTORY;

SELECT START_DATE, START_DATE+7 FROM JOB_HISTORY;





