SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'David';

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID = 'AC_ACCOUNT';

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
  AND SALARY > 5000;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_a%a';

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20
   OR DEPARTMENT_ID = 30;

SELECT FIRST_NAME, LAST_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_ID, EMAIL
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL AND
      DEPARTMENT_ID = 50
   OR DEPARTMENT_ID = 80
ORDER BY EMAIL DESC;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n%n%';

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 4
ORDER BY DEPARTMENT_ID DESC NULLS LAST;

SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 7000
  AND COMMISSION_PCT IS NULL
  AND JOB_ID IN ('PU_CLERK', 'ST_MAN', 'ST_CLERK');

-- SELECT *
-- FROM EMPLOYEES
-- WHERE FIRST_NAME LIKE '%\_%' ESCAPE '%';

-- SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE 'ST\_C%' ESCAPE '\' ;

SELECT JOB_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID >= 120
  AND JOB_ID != 'IT_PROG'
ORDER BY JOB_ID DESC, FIRST_NAME;