SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'SA_MAN';

SELECT * FROM EMPLOYEES WHERE NOT (JOB_ID = 'SA_MAN');

SELECT * FROM EMPLOYEES WHERE NOT (JOB_ID = 'SA_MAN') AND COMMISSION_PCT IS NOT NULL OR FIRST_NAME LIKE 'G%e' OR LAST_NAME LIKE 'G%a' AND SALARY > 10000;

SELECT * FROM EMPLOYEES WHERE  LAST_NAME NOT LIKE 'K%';

SELECT * FROM EMPLOYEES WHERE JOB_ID NOT IN ('SA_MAN', 'ST_CLERK');

SELECT * FROM EMPLOYEES WHERE SALARY NOT BETWEEN 5000 and 10000;

SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL AND LAST_NAME NOT LIKE '%n' AND FIRST_NAME NOT LIKE ' %n';