SELECT *
FROM EMPLOYEES;


SELECT FIRST_NAME name, SALARY
FROM EMPLOYEES
ORDER BY SALARY;

SELECT FIRST_NAME name, SALARY
FROM EMPLOYEES
ORDER BY FIRST_NAME;

SELECT FIRST_NAME name, SALARY
FROM EMPLOYEES
ORDER BY FIRST_NAME, SALARY;

SELECT *
FROM EMPLOYEES;

SELECT FIRST_NAME name, SALARY
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG'
ORDER BY FIRST_NAME;

SELECT FIRST_NAME name, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG'
ORDER BY HIRE_DATE;

SELECT FIRST_NAME name, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT FIRST_NAME name, SALARY, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

SELECT LAST_NAME, SALARY, HIRE_DATE, HIRE_DATE + SALARY * 2 multiplay_date
FROM EMPLOYEES
WHERE EMPLOYEE_ID > 120
ORDER BY multiplay_date;

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY COMMISSION_PCT DESC;

SELECT *
FROM EMPLOYEES
ORDER BY COMMISSION_PCT DESC NULLS LAST;




