SELECT *
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE SALARY = 4800
   OR SALARY > 7700 AND SALARY < 9000 AND COMMISSION_PCT IS NOT NULL AND HIRE_DATE > '01.01.99';

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'D%' AND COMMISSION_PCT IS NOT NULL
   OR SALARY > 7000 AND COMMISSION_PCT IS NOT NULL
   OR JOB_ID = 'SA_REP' AND COMMISSION_PCT IS NOT NULL;