SELECT * FROM EMPLOYEES WHERE SALARY > 12000 AND COMMISSION_PCT IS NOT NULL ;

SELECT FIRST_NAME, LAST_NAME, SALARY  FROM EMPLOYEES WHERE SALARY > 10000;

SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Susan';

SELECT * FROM EMPLOYEES WHERE HIRE_DATE='10.10.1997';

SELECT * FROM DEPARTMENTS WHERE LOCATION_ID = 1700 AND MANAGER_ID IS NOT NULL;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = MANAGER_ID;

SELECT * FROM EMPLOYEES WHERE MANAGER_ID = 1000/10+1;

SELECT * FROM JOB_HISTORY WHERE JOB_ID = 'ST_CLERK';

SELECT * FROM JOB_HISTORY WHERE END_DATE = START_DATE+364;

