SELECT *
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__n%'
  AND COMMISSION_PCT IS NOT NULL;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%'
  AND JOB_ID = 'SA_REP';

SELECT *
FROM EMPLOYEES
WHERE (FIRST_NAME LIKE '__n%'
    AND COMMISSION_PCT IS NOT NULL)
   OR (FIRST_NAME LIKE 'A%'
    AND JOB_ID = 'SA_REP');

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, JOB_ID, COMMISSION_PCT
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%i%'
    AND SALARY > EMPLOYEE_ID * 50
   OR JOB_ID IN ('IT_PROD', 'PU_CLERK') AND COMMISSION_PCT IS NULL;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;


