SELECT TRIM(TRAILING 'Q' FROM 'QQQQQASDQQQQQ')
FROM DUAL;

SELECT TRIM(LEADING 'Q' FROM 'QQQQQASDQQQQQ')
FROM DUAL;

SELECT TRIM(BOTH 'Q' FROM 'QQQQQASDQQQQQ')
FROM DUAL;

SELECT TRIM('  Aleksey Elchin  ') trimmed
FROM DUAL;

SELECT TRIM(BOTH 7 FROM '7773453455577') trimmed
FROM DUAL;