SELECT END_DATE
FROM JOB_HISTORY;

SELECT END_DATE, ADD_MONTHS(END_DATE, 4)
FROM JOB_HISTORY;

SELECT ADD_MONTHS('30.09.19', 3)
FROM DUAL;

SELECT ADD_MONTHS('31.12.19', 2)
FROM DUAL;

SELECT *
FROM EMPLOYEES
WHERE MONTHS_BETWEEN('01.01.10', HIRE_DATE) > 60;