SELECT *
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 10;

SELECT ROUND(SALARY)
FROM EMPLOYEES
WHERE LENGTH(SALARY) = 4;

SELECT *
FROM EMPLOYEES
WHERE MOD(SALARY, 1000) = 0;

SELECT PHONE_NUMBER, SUBSTR(PHONE_NUMBER, 1, 3)
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '___.___.____';


SELECT *
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME, -1) = 'm'
  AND LENGTH(FIRST_NAME) > 5;


SELECT NEXT_DAY(SYSDATE, 'Пятница') NEXT_FRIDAY
FROM DUAL;


SELECT *
FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) > 150;


SELECT FIRST_NAME, REPLACE(PHONE_NUMBER, '.', '-') NEW_PHONE_NUMBER
FROM EMPLOYEES;


SELECT HIRE_DATE, ROUND(HIRE_DATE, 'MM'), TRUNC(HIRE_DATE, 'YYYY')
FROM EMPLOYEES;


SELECT RPAD(FIRST_NAME, 10, '$'), LPAD(LAST_NAME, 15, '!')
FROM EMPLOYEES;

SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a', 1, 2)
FROM EMPLOYEES;


SELECT SALARY,
       SALARY * 3.12378,
       ROUND(SALARY * 3.12378),
       TRUNC(SALARY * 3.12378, -4) / 1000
FROM EMPLOYEES;


SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE, 6), LAST_DAY(HIRE_DATE)
FROM EMPLOYEES;
