SELECT FIRST_NAME, LENGTH(FIRST_NAME) dlina
FROM EMPLOYEES;

SELECT LENGTH('Aleksey Elchin')
FROM DUAL;

SELECT SALARY, LENGTH(SALARY), HIRE_DATE, LENGTH(HIRE_DATE)
FROM EMPLOYEES;

SELECT *
FROM COUNTRIES;

SELECT COUNTRY_NAME, LENGTH(COUNTRY_NAME) length
FROM COUNTRIES
WHERE LENGTH(COUNTRY_NAME) > 9;

SELECT COUNTRY_NAME, LENGTH(COUNTRY_NAME) length
FROM COUNTRIES
ORDER BY LENGTH(COUNTRY_NAME) DESC;
