SELECT MOD(7, 3)
FROM DUAL;

SELECT MOD(9, 3)
FROM DUAL;

SELECT MOD(3, 9)
FROM DUAL;

SELECT MOD(0, 9)
FROM DUAL;

SELECT MOD(3.1, 2.2)

FROM DUAL;

SELECT *
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) = 0;

SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, MOD(EMPLOYEE_ID, 3) + 1 team
FROM EMPLOYEES
ORDER BY MOD(EMPLOYEE_ID, 3) + 1;