SELECT FIRST_NAME,
       LAST_NAME,
       HIRE_DATE,
       ROUND(HIRE_DATE, 'YYYY')
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT FIRST_NAME,
       LAST_NAME,
       HIRE_DATE,
       ROUND(HIRE_DATE, 'Q')
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);

SELECT FIRST_NAME,
       LAST_NAME,
       HIRE_DATE,
       ROUND(HIRE_DATE, 'MM')
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (120, 121);
