SELECT *
FROM EMPLOYEES;

SELECT EMAIL, SUBSTR(EMAIL, 6) CUTESTR
FROM EMPLOYEES
WHERE SUBSTR(EMAIL, 6) IS NOT NULL;

SELECT SUBSTR('Привет как дела', 7, 25)
FROM DUAL;

SELECT SALARY, SUBSTR(SALARY, 2, 3)
FROM EMPLOYEES;

SELECT HIRE_DATE, SUBSTR(HIRE_DATE, 2, 3)
FROM EMPLOYEES;

SELECT SUBSTR('Привет как дела', -9)
FROM DUAL;

SELECT SUBSTR('Привет как дела', -4)
FROM DUAL;

SELECT SUBSTR('Привет как дела', -4, 2)
FROM DUAL;