SELECT COALESCE(1, null, 2)
FROM DUAL;

SELECT COALESCE(null, null, 'hello', 'world')
FROM DUAL;

SELECT COALESCE(17, 18)
FROM DUAL;

SELECT FIRST_NAME, COMMISSION_PCT, MANAGER_ID, SALARY, COALESCE(COMMISSION_PCT, MANAGER_ID, SALARY) info
FROM EMPLOYEES;