SELECT *
FROM EMPLOYEES
WHERE INSTR(LOWER(FIRST_NAME), 'b') > 0;

SELECT *
FROM EMPLOYEES
WHERE INSTR(LOWER(FIRST_NAME), 'a', 1, 2,) > 0;

SELECT SUBSTR(DEPARTMENT_NAME, 1, INSTR(DEPARTMENT_NAME, ' ') - 1) first_word
FROM DEPARTMENTS
WHERE INSTR(DEPARTMENT_NAME, ' ') > 0;

SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 2, LENGTH(FIRST_NAME) - 2) new_name
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE LENGTH(SUBSTR(JOB_ID, INSTR(JOB_ID, ' ') + 1)) > 3
  AND SUBSTR(JOB_ID, INSTR(JOB_ID, '_') + 1) != 'CLERK';

SELECT *
FROM EMPLOYEES `
WHERE TO_CHAR(HIRE_DATE, 'DD') = '01';

SELECT *
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = '1997';

SELECT FIRST_NAME, TO_CHAR(HIRE_DATE, 'fmddth "of " Month, YYYY ') hire_date
FROM EMPLOYEES;

SELECT FIRST_NAME, TO_CHAR(SALARY + SALARY * 0.20, '$999,999.00') new_salary
FROM EMPLOYEES;

SELECT SYSDATE                      now,
       SYSDATE + 1 / (24 * 60 * 60) plus_secobd,
       SYSDATE + 1 / (24 * 60)      plus_minute,
       SYSDATE + 1 / 24             plus_hour,
       SYSDATE + 1                  plus_day,
       ADD_MONTHS(SYSDATE, 1)       plus_month,
       ADD_MONTHS(SYSDATE, 12)      plus_year
FROM DUAL;


SELECT FIRST_NAME, SALARY, SALARY + TO_NUMBER('$12,345 .55', '$99,999.99')
FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, TO_CHAR(SALARY + SALARY * NVL(COMMISSION_PCT, 0), '$99,999.00') full_salary
FROM EMPLOYEES;

SELECT FIRST_NAME, COMMISSION_PCT, NVL2(COMMISSION_PCT, 'yes', 'no')
FROM EMPLOYEES;

SELECT FIRST_NAME, COALESCE(COMMISSION_PCT, MANAGER_ID, SALARY)
FROM EMPLOYEES;

SELECT

