SELECT NVL(18, 19)
FROM DUAL;

SELECT NVL(null, 19)
FROM DUAL;

SELECT NVL(null, null)
FROM DUAL;

SELECT FIRST_NAME, NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES;

SELECT FIRST_NAME, NVL(SUBSTR(FIRST_NAME, 6), 'NAME IS TOO SHORT')
FROM EMPLOYEES;

SELECT FIRST_NAME, COMMISSION_PCT, NVL(SALARY * COMMISSION_PCT, 500) bonus
FROM EMPLOYEES;

-- NVL2

SELECT NVL2(17, 18, 19)
FROM DUAL;

SELECT FIRST_NAME, NVL2(COMMISSION_PCT, COMMISSION_PCT, 0)
FROM EMPLOYEES;

SELECT FIRST_NAME, NVL2(COMMISSION_PCT, 'has commision', 'has not commision')
FROM EMPLOYEES;