SELECT NULLIF(18, 18)
FROM DUAL;

SELECT NULLIF(17, 18)
FROM DUAL;

SELECT NULLIF(TO_CHAR(15), TO_CHAR(1 || 5))
FROM DUAL;

SELECT NULLIF('18.09.87', '18/09/87')
FROM DUAL;

SELECT NULLIF(TO_DATE('18.09.87'), TO_DATE('18/09/87'))
FROM DUAL;

SELECT COUNTRY_ID,
       COUNTRY_NAME,
       NVL2(NULLIF(COUNTRY_ID, UPPER(
           SUBSTR(COUNTRY_NAME, 1, 2))), 'SOVPADENY NET', 'SOVPADENY NAIDENO') sravnenie
FROM COUNTRIES;