SELECT TO_CHAR('23-SEP-83')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'Y')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'RR')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YEAR')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'Year')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MM')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MON')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'mon')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'Month')
FROM DUAL;

SELECT HIRE_DATE, TO_CHAR(HIRE_DATE, 'Month')
FROM EMPLOYEES;

SELECT HIRE_DATE, TO_CHAR(HIRE_DATE, 'fmMonth') || 'Hello'
FROM EMPLOYEES;

SELECT HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'fmMonth') = 'August'

SELECT TO_CHAR(SYSDATE, 'd')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DDD')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DAY')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'W')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'WW')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'Q')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'CC')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'A.M.')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'P.M.')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'HH24')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MI')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'SSSSS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DAY!Mon?yyyy')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, '"quater " q " of "year ')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DDth " of " mm')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MI')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MIth')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MIthsp')
FROM DUAL;

SELECT 'my collegue with ID = ' || EMPLOYEE_ID || ' and job_id = ' || FIRST_NAME || ' joined us on ' ||
       TO_CHAR(HIRE_DATE, 'DD.MM.YYYY')
FROM EMPLOYEES;






