DELETE
FROM NEW_EMPS
WHERE JOB IN (SELECT JOB_ID
             from EMPLOYEES
             WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE MANAGER_ID = 100));

SELECT *
FROM NEW_EMPS;