CREATE TABLE EMPS_WITH_HIGHT_SALARY
(
    NAME   VARCHAR(20),
    SALARY INTEGER
);

CREATE TABLE EMPS_WITH_DEPT_100
(
    NAME   VARCHAR(20),
    SALARY INTEGER
);

CREATE TABLE SOME_EMPS
(
    NAME   VARCHAR(20),
    SALARY INTEGER
);

INSERT ALL
    WHEN DEPARTMENT_ID = 100 THEN
    INTO EMPS_WITH_DEPT_100
VALUES (FIRST_NAME, SALARY)
    WHEN SALARY > 15000 THEN
INTO EMPS_WITH_HIGHT_SALARY (NAME)
VALUES (LAST_NAME)
    WHEN 5 = 5 THEN
INTO SOME_EMPS (NAME, SALARY)
VALUES (FIRST_NAME, SALARY)
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 5;

SELECT *
FROM SOME_EMPS;

SELECT *
FROM EMPS_WITH_HIGHT_SALARY;








