CREATE TABLE NEW_EMPS
(
    EMP_ID     INTEGER,
    NAME       VARCHAR(20),
    START_DATE DATE,
    JOB        VARCHAR2(10)
);

DROP TABLE NEW_EMPS;

INSERT INTO NEW_EMPS (EMP_ID, NAME, START_DATE)
    (SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
     FROM EMPLOYEES
     WHERE EMPLOYEE_ID > 200);

SELECT *
FROM NEW_EMPS;

INSERT INTO NEW_EMPS
    (SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, JOB_ID
     FROM EMPLOYEES
     WHERE EMPLOYEE_ID > 200);