UPDATE EMPLOYEES
SET SALARY = 5000
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Marketing');

SELECT FIRST_NAME, SALARY, DE.DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE
              ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
WHERE EM.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Marketing');

UPDATE EMPLOYEES
SET SALARY    = (SELECT MAX(SALARY) FROM EMPLOYEES),
    HIRE_DATE = (SELECT MIN(START_DATE) FROM JOB_HISTORY)
WHERE EMPLOYEE_ID = 100;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

UPDATE EMPLOYEES
SET SALARY = (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 5)
WHERE EMPLOYEE_ID = 100;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 100;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 5;








