CREATE TABLE STUDENTS
(
    STUDENT_ID  INTEGER,
    NAME        VARCHAR2(15),
    START_DATE  DATE         DEFAULT ROUND(SYSDATE),
    SCHOLARSHIP NUMBER(6, 2),
    AVG_SCORE   NUMBER(4, 2) DEFAULT 5
) ORGANIZATION HEAP;

SELECT *
FROM STUDENTS;


INSERT INTO STUDENTS (STUDENT_ID, NAME, START_DATE, SCHOLARSHIP, AVG_SCORE)
VALUES (1, 'Aleksey', TO_DATE('18-02-19'), 1500.3, 7.8);

SELECT *
FROM STUDENTS;

INSERT INTO STUDENTS (STUDENT_ID, NAME, START_DATE, SCHOLARSHIP, AVG_SCORE)
VALUES (2, 'Ivan', TO_DATE('18-02-20'), 8500, 8);

SELECT *
FROM STUDENTS;