SELECT *
FROM DBA_OBJECTS;

SELECT *
FROM USER_OBJECTS;

SELECT OBJECT_TYPE, COUNT(OBJECT_TYPE)
FROM USER_OBJECTS
GROUP BY OBJECT_TYPE
ORDER BY OBJECT_TYPE;

SELECT OBJECT_TYPE, COUNT(OBJECT_TYPE)
FROM ALL_OBJECTS
GROUP BY OBJECT_TYPE
ORDER BY OBJECT_TYPE;

SELECT TABLE_NAME
FROM USER_TABLES;

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS;

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'DEPARTMENTS';