SELECT *
FROM NEW_EMPS;


CREATE TABLE NEW_EMPS2 AS (SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
                           FROM EMPLOYEES);

SELECT *
FROM NEW_EMPS2;

COMMIT;

CREATE TABLE NEW_DEP AS (SELECT DEPARTMENT_NAME, MAX(SALARY) max_salary, MIN(SALARY) min_salary
                         FROM EMPLOYEES EM
                                  JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
                         GROUP BY DEPARTMENT_NAME);

SELECT *
FROM NEW_DEP;


CREATE TABLE REGIONS2 AS (SELECT *
                          FROM REGIONS
                          WHERE 5 = 6);

SELECT *
FROM REGIONS2;