SELECT *
FROM STUDENTS;

ALTER TABLE STUDENTS
    ADD (COURSE NUMBER DEFAULT 3);

SELECT *
FROM STUDENTS;

ALTER TABLE STUDENTS
    MODIFY (AVG_SCORE NUMBER(5, 3));

ALTER TABLE STUDENTS
    MODIFY (START_DATE DATE DEFAULT NULL);

SELECT *
FROM STUDENTS;


INSERT INTO STUDENTS (STUDENT_ID, NAME, SCHOLARSHIP)
VALUES (555, 'Nina', 7300);

SELECT *
FROM STUDENTS;

ALTER TABLE STUDENTS
    DROP COLUMN SCHOLARSHIP;

SELECT *
FROM STUDENTS;

ALTER TABLE STUDENTS RENAME COLUMN STUDENT_ID TO ID;

SELECT *
FROM STUDENTS;

ALTER TABLE STUDENTS
    READ ONLY;

SELECT *
FROM STUDENTS;


DELETE
FROM STUDENTS
WHERE ID = 100;

DROP TABLE STUDENTS;

SELECT *
FROM STUDENTS;

CREATE TABLE STUDENTS
(
    STUDENT_ID  INTEGER,
    NAME        VARCHAR2(15),
    START_DATE  DATE         DEFAULT ROUND(SYSDATE),
    SCHOLARSHIP NUMBER(6, 2),
    AVG_SCORE   NUMBER(4, 2) DEFAULT 5
) ORGANIZATION HEAP;

INSERT INTO STUDENTS (STUDENT_ID, NAME, START_DATE, SCHOLARSHIP, AVG_SCORE)
VALUES (1, 'Aleksey', TO_DATE('18-02-19'), 1500.3, 7.8);


SELECT *
FROM STUDENTS;

INSERT INTO STUDENTS (STUDENT_ID, NAME)
VALUES (23123123, 'Max');

SELECT STUDENT_ID, NAME
FROM STUDENTS
WHERE STUDENT_ID = 23123123;






