CREATE TABLE ADDRESS
(
    ID      NUMBER,
    COUNTRY VARCHAR(25),
    CITY    VARCHAR(25),
    CONSTRAINT ad_id_un UNIQUE (ID)
);

SELECT *
FROM ADDRESS;

CREATE TABLE FRIENDS
(
    ID         NUMBER,
    NAME       VARCHAR(25),
    EMAIL      VARCHAR(25),
    ADDRESS_ID NUMBER,
    BIRTHDAY   DATE,
    CONSTRAINT fk_fr FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) ON DELETE SET NULL
);

DROP TABLE FRIENDS;

ALTER TABLE FRIENDS
    MODIFY (NAME CONSTRAINT ch CHECK (NAME > 3));

SELECT *
FROM FRIENDS;

CREATE UNIQUE INDEX un_idx ON FRIENDS (ID);

SELECT *
FROM FRIENDS;


ALTER TABLE FRIENDS
    ADD CONSTRAINT fr_id_pk PRIMARY KEY (ID);

SELECT *
FROM FRIENDS;

CREATE UNIQUE INDEX fr_email_in ON FRIENDS (EMAIL);

ALTER TABLE FRIENDS
    MODIFY (EMAIL CONSTRAINT fr_email_nn NOT NULL);

SELECT *
FROM FRIENDS;

DROP TABLE FRIENDS;

DROP TABLE ADDRESS;


