SELECT *
FROM STUDENTS;

DROP TABLE STUDENTS;

CREATE TABLE STUDENTS
(
    ID         NUMBER,
    NAME       VARCHAR2(15),
    COURSE     NUMBER DEFAULT 3,
    FACULTY_ID INTEGER,
    CONSTRAINT con1 UNIQUE (COURSE)
);

CREATE BITMAP INDEX bt_idx1 ON STUDENTS (FACULTY_ID);

SELECT *
FROM STUDENTS;

SELECT *
FROM v$version;