CREATE TABLE STUDENTS
(
    ID          NUMBER,
    NAME        VARCHAR2(15),
    COURSE      NUMBER,
    FACULTY_ID  INTEGER,
    AVG_SCORE   NUMBER(5, 2),
    START_DATE  DATE,
    SCHOLARSHIP INTEGER
);

CREATE TABLE FACULTIES
(
    ID   NUMBER,
    NAME VARCHAR2(15)
)