SELECT *
FROM EMPLOYEES;

CREATE VIEW fin_emp AS
SELECT EMPLOYEE_ID, JOB_ID, SALARY
FROM EMPLOYEES;

SELECT *
FROM fin_emp;

CREATE VIEW fin_emp_3 AS
SELECT DEPARTMENT_NAME, SUM(SALARY) sum_salary, COUNT(*) emploees
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (DE.DEPARTMENT_ID = EM.DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT *
FROM fin_emp_3
ORDER BY fin_emp_3.SUM_SALARY DESC;

SELECT *
FROM fin_emp_2
WHERE fin_emp_2.SUM_SALARY > 10000
ORDER BY fin_emp_2.SUM_SALARY DESC;

SELECT *
FROM EMPLOYEES;









