SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, COUNT(*) total_employes, MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY total_employes DESC;

SELECT JOB_ID,
       COUNT(*)    employes,
       ROUND(AVG(SALARY)),
       MIN(SALARY),
       MAX(SALARY),
       SUM(SALARY) total_salary
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 4
  AND SALARY > 5000
--   AND COMMISSION_PCT IS NOT NULL
GROUP BY JOB_ID
ORDER BY employes DESC;

SELECT MAX(HIRE_DATE),
       MIN(FIRST_NAME),
       COUNT(*),
       ROUND(AVG(SALARY)),
       SUM(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT TO_CHAR(HIRE_DATE, 'Month'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'Month')
ORDER BY COUNT(*) DESC;

SELECT LOCATION_ID, COUNT(*)
FROM DEPARTMENTS
GROUP BY LOCATION_ID;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY COUNT(*) DESC;

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_ID, JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_ID, MANAGER_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, MANAGER_ID
ORDER BY COUNT(*) DESC;

SELECT JOB_ID, COUNT(*), TO_CHAR(HIRE_DATE, 'YYYY') year, COMMISSION_PCT, SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID IN ('ST_CLERK', 'SA_REP', 'SH_CLERK')
  AND EMPLOYEE_ID > 115
GROUP BY JOB_ID, TO_CHAR(HIRE_DATE, 'YYYY'), COMMISSION_PCT
ORDER BY SUM(SALARY) DESC, year;

SELECT *
FROM EMPLOYEES
WHERE SALARY > 10000;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 3
ORDER BY COUNT(*) DESC;

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING LENGTH(JOB_ID) > 3
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_ID, COUNT(*), ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 3
   AND ROUND(AVG(SALARY)) > 5000
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_ID, COUNT(*), ROUND(AVG(SALARY))
FROM EMPLOYEES
WHERE EMPLOYEE_ID > 50
  AND SALARY > 10000
GROUP BY DEPARTMENT_ID;







