SELECT DEPARTMENT_ID,
       COUNT(*),
       MAX(SALARY),
       MIN(SALARY),
       TO_CHAR(MIN(HIRE_DATE), 'DD-MM-YYYY') min,
       TO_CHAR(MAX(HIRE_DATE), 'DD-MM-YYYY') max
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY COUNT(*) DESC;


SELECT SUBSTR(FIRST_NAME, 1, 1) first_char, COUNT(*)
FROM EMPLOYEES
GROUP BY SUBSTR(FIRST_NAME, 1, 1)
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_ID, SALARY, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, SALARY
ORDER BY COUNT(*) DESC;

SELECT TO_CHAR(HIRE_DATE, 'Day') day, COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'Day')
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 30
   AND SUM(SALARY) > 300000;

SELECT REGION_ID, SUM(LENGTH(COUNTRY_NAME))
FROM COUNTRIES
GROUP BY REGION_ID
HAVING SUM(LENGTH(COUNTRY_NAME)) > 50;

SELECT JOB_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY ROUND(AVG(SALARY)) DESC;

SELECT DEPARTMENT_ID, COUNT(DISTINCT JOB_ID), SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(DISTINCT JOB_ID) > 1
ORDER BY SUM(SALARY) DESC;

SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY SUM(SALARY) DESC;

SELECT DEPARTMENT_ID, JOB_ID, MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING ROUND(AVG(SALARY)) > 10000;

SELECT DEPARTMENT_ID, JOB_ID, MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID > 80
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING ROUND(AVG(SALARY)) > 10000;

SELECT MANAGER_ID, COUNT(*), ROUND(AVG(SALARY))
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
  AND COMMISSION_PCT IS NULL
GROUP BY MANAGER_ID
HAVING ROUND(AVG(SALARY)) BETWEEN 6000 AND 9000
ORDER BY ROUND(AVG(SALARY)) DESC;

SELECT ROUND(MAX(AVG(SALARY)), -3)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;












