SELECT MIN(DISTINCT SALARY), ROUND(AVG(DISTINCT SALARY)), MAX(DISTINCT SALARY)
FROM EMPLOYEES;

SELECT MIN(DISTINCT SALARY), ROUND(AVG(DISTINCT SALARY)), MAX(DISTINCT SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

SELECT TO_CHAR(MIN(HIRE_DATE), 'DD-MM-YYYY'), TO_CHAR(MAX(HIRE_DATE), 'DD-MM-YYYY')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

SELECT MIN(LENGTH(FIRST_NAME)), MAX(LENGTH(FIRST_NAME))
FROM EMPLOYEES;

SELECT COUNT(SALARY), SUM(SALARY), ROUND(AVG(SALARY)), MIN(SALARY)
FROM EMPLOYEES;



