SELECT SUM(ALL SALARY)
FROM EMPLOYEES;

SELECT 5 + NULL
FROM DUAL;

SELECT SUM(DISTINCT COMMISSION_PCT)
FROM EMPLOYEES;

SELECT SUM(SALARY), SUM(DISTINCT SALARY)
FROM EMPLOYEES;

SELECT SUM(FIRST_NAME)
FROM EMPLOYEES;

SELECT SUM('7')
FROM EMPLOYEES;

SELECT SYSDATE - HIRE_DATE
FROM EMPLOYEES;

SELECT ROUND(SUM(SYSDATE - HIRE_DATE) / 365) working_days
FROM EMPLOYEES;

SELECT SUM(LENGTH(FIRST_NAME))
FROM EMPLOYEES;

SELECT LENGTH(FIRST_NAME)
FROM EMPLOYEES;

SELECT ROUND(SUM(LENGTH(FIRST_NAME)) / COUNT(*)) awerage_len gth_of_neme
FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY), 2)
FROM EMPLOYEES;

SELECT ROUND(SUM(SALARY) / COUNT(*), 2)
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT AVG(DISTINCT SALARY)
FROM EMPLOYEES;

SELECT AVG(DISTINCT COMMISSION_PCT)
FROM EMPLOYEES;

SELECT COUNT(*), SUM(SALARY), AVG(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT AVG(7)
FROM EMPLOYEES;

SELECT ROUND(AVG(SYSDATE - HIRE_DATE) / 365)
FROM EMPLOYEES;

SELECT ROUND(AVG(NVL(COMMISSION_PCT, 0)), 5)
FROM EMPLOYEES;