SELECT REGION_NAME, COUNT(*)
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
         JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
         JOIN REGIONS R ON (C.REGION_ID = R.REGION_ID)
GROUP BY REGION_NAME;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, JOB_ID, STREET_ADDRESS, COUNTRY_NAME, REGION_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
         JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
         JOIN REGIONS R ON (C.REGION_ID = R.REGION_ID);

SELECT MAN.FIRST_NAME, COUNT(*)
FROM EMPLOYEES EMP
         JOIN EMPLOYEES MAN ON (EMP.MANAGER_ID = MAN.MANAGER_ID)
GROUP BY MAN.FIRST_NAME
-- HAVING COUNT(*) > 6
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_NAME, COUNT(*)
FROM EMPLOYEES
         JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*) > 6
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_NAME
FROM EMPLOYEES E
         RIGHT JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE FIRST_NAME IS NULL;

SELECT EMP.*
FROM EMPLOYEES EMP
         JOIN EMPLOYEES MAN ON (EMP.MANAGER_ID = MAN.EMPLOYEE_ID)
WHERE TO_CHAR(MAN.HIRE_DATE, 'YYYY') = '2005'
  AND EMP.HIRE_DATE < TO_DATE('01-01-2005', 'DD=MM-YYYY');

SELECT COUNTRY_NAME, REGION_NAME
FROM COUNTRIES
         NATURAL JOIN REGIONS;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES E
         JOIN JOBS J ON (E.JOB_ID = J.JOB_ID AND SALARY < MIN_SALARY + 1000);

SELECT DISTINCT FIRST_NAME,
                LAST_NAME,
                CITY,
                COUNTRY_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
         JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID;

SELECT DISTINCT FIRST_NAME,
                LAST_NAME,
                CITY,
                COUNTRY_NAME
FROM EMPLOYEES E
         FULL OUTER JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         FULL OUTER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
         FULL OUTER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
ORDER BY FIRST_NAME;


