SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM DEPARTMENTS DE
         LEFT OUTER JOIN EMPLOYEES EM ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);

SELECT FIRST_NAME, SALARY, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY * 2 < MAX_SALARY);

SELECT FIRST_NAME, SALARY, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         LEFT OUTER JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY * 2 < MAX_SALARY);

SELECT POSTAL_CODE, CITY, DEPARTMENT_NAME, DE.LOCATION_ID
FROM LOCATIONS LO
         LEFT OUTER JOIN DEPARTMENTS DE ON (DE.LOCATION_ID = LO.LOCATION_ID);

SELECT DEPARTMENT_NAME, DE.DEPARTMENT_ID
FROM DEPARTMENTS DE
         LEFT OUTER JOIN EMPLOYEES EM ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
WHERE FIRST_NAME IS NULL;