SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID
FROM EMPLOYEES;

SELECT EMP2.FIRST_NAME manager_name, COUNT(*)
FROM EMPLOYEES EMP1
         JOIN EMPLOYEES EMP2 ON (EMP1.MANAGER_ID = EMP2.EMPLOYEE_ID)
GROUP BY EMP2.FIRST_NAME
ORDER BY COUNT(*) DESC;