SELECT FIRST_NAME, LAST_NAME, J.JOB_ID, START_DATE, END_DATE, E.EMPLOYEE_ID, J.EMPLOYEE_ID
FROM EMPLOYEES E
         JOIN JOB_HISTORY J ON (E.EMPLOYEE_ID = J.EMPLOYEE_ID);

SELECT *
FROM REGIONS;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM DEPARTMENTS D
         JOIN REGIONS R ON (R.REGION_ID * 10 = D.DEPARTMENT_ID);

SELECT FIRST_NAME, LAST_NAME, J.JOB_ID, START_DATE, END_DATE
FROM EMPLOYEES E
         JOIN JOB_HISTORY J USING (EMPLOYEE_ID, DEPARTMENT_ID);

SELECT FIRST_NAME, LAST_NAME, SALARY, J.JOB_ID, START_DATE, END_DATE
FROM EMPLOYEES E
         JOIN JOB_HISTORY J ON (E.EMPLOYEE_ID = J.EMPLOYEE_ID OR E.DEPARTMENT_ID = J.DEPARTMENT_ID)
WHERE SALARY > 15000;

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES
         JOIN DEPARTMENTS D ON (EMPLOYEE_ID = D.MANAGER_ID);