SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT EMPLOYEES.SALARY, EMPLOYEES.FIRST_NAME
FROM EMPLOYEES;

SELECT SALARY, FIRST_NAME
FROM EMPLOYEES E;

SELECT E.SALARY, E.FIRST_NAME
FROM EMPLOYEES E;

SELECT *
FROM REGIONS;

SELECT *
FROM COUNTRIES;

SELECT C.COUNTRY_NAME, R.REGION_NAME
FROM REGIONS R
         NATURAL JOIN COUNTRIES C;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME, DEPARTMENT_ID, MANAGER_ID
FROM EMPLOYEES
         NATURAL JOIN DEPARTMENTS;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM COUNTRIES;

SELECT *
FROM EMPLOYEES
         NATURAL JOIN COUNTRIES;

SELECT *
FROM JOB_HISTORY;

SELECT *
FROM EMPLOYEES
         NATURAL JOIN JOB_HISTORY;

SELECT C.COUNTRY_NAME, COUNTRY_ID, R.REGION_NAME, REGION_ID
FROM REGIONS R
         NATURAL JOIN COUNTRIES C
WHERE REGION_NAME = 'Europe'



