SELECT *
FROM JOBS;

SELECT FIRST_NAME, SALARY, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY * 2 < MAX_SALARY);

SELECT FIRST_NAME, SALARY, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY = MAX_SALARY);

SELECT FIRST_NAME, SALARY, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY < MAX_SALARY);

SELECT FIRST_NAME, SALARY, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY BETWEEN 5000 AND 10000);