SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM DEPARTMENTS DE
         LEFT OUTER JOIN EMPLOYEES EM ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);

SELECT *
FROM COUNTRIES;

SELECT *
FROM LOCATIONS;

SELECT COUNTRY_NAME, CITY, STREET_ADDRESS
FROM LOCATIONS LS
         RIGHT OUTER JOIN COUNTRIES CT ON (CT.COUNTRY_ID = LS.COUNTRY_ID);