SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME, E.MANAGER_ID, D.MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES E
         JOIN DEPARTMENTS D USING (DEPARTMENT_ID);

SELECT *
FROM REGIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM REGIONS
         JOIN COUNTRIES USING (REGION_ID);

SELECT *
FROM JOB_HISTORY;

SELECT FIRST_NAME, LAST_NAME, J.JOB_ID, START_DATE, END_DATE
FROM EMPLOYEES E
         JOIN JOB_HISTORY J USING (EMPLOYEE_ID, DEPARTMENT_ID)