SELECT *
FROM REGIONS;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT *
FROM LOCATIONS
         NATURAL JOIN COUNTRIES
         NATURAL JOIN REGIONS;

SELECT *
FROM LOCATIONS L
         JOIN COUNTRIES C USING (COUNTRY_ID)
         JOIN REGIONS USING (REGION_ID);

SELECT FIRST_NAME, LAST_NAME, JH.JOB_ID, START_DATE, END_DATE, EM.EMPLOYEE_ID, DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN JOB_HISTORY JH ON (EM.EMPLOYEE_ID = JH.EMPLOYEE_ID)
         JOIN DEPARTMENTS DE ON (JH.DEPARTMENT_ID = DE.DEPARTMENT_ID);

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);


SELECT DEPARTMENT_NAME, MIN(SALARY), MAX(SALARY)
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME DESC;
