SELECT REGION_NAME, COUNT(*)
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
         JOIN LOCATIONS LC ON (DE.LOCATION_ID = LC.LOCATION_ID)
         JOIN COUNTRIES CN ON (LC.COUNTRY_ID = CN.COUNTRY_ID)
         JOIN REGIONS RG ON (CN.REGION_ID = RG.REGION_ID)
GROUP BY REGION_NAME;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, JOB_ID, STREET_ADDRESS, COUNTRY_NAME, REGION_NAME
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
         JOIN LOCATIONS LC ON (DE.LOCATION_ID = LC.LOCATION_ID)
         JOIN COUNTRIES CN ON (LC.COUNTRY_ID = CN.COUNTRY_ID)
         JOIN REGIONS RE ON (CN.REGION_ID = RE.REGION_ID);

SELECT man.FIRST_NAME, COUNT(*)
FROM EMPLOYEES emp
         JOIN EMPLOYEES man ON (emp.MANAGER_ID = man.MANAGER_ID)
GROUP BY man.FIRST_NAME
HAVING COUNT(*) > 6
ORDER BY COUNT(*) DESC;

SELECT DEPARTMENT_NAME, COUNT(*)
FROM EMPLOYEES
         JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING COUNT(*) > 30;

SELECT DEPARTMENT_NAME
FROM EMPLOYEES EM
         RIGHT JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
WHERE FIRST_NAME IS NULL;

SELECT COUNTRY_NAME, REGION_NAME
FROM COUNTRIES
         NATURAL JOIN REGIONS;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY < MIN_SALARY + 1000);

SELECT DISTINCT FIRST_NAME, LAST_NAME, COUNTRY_NAME
FROM EMPLOYEES E
         FULL OUTER JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         FULL OUTER JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
         FULL OUTER JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID);


SELECT DISTINCT COUNTRY_NAME, COUNT(*)
FROM EMPLOYEES E
         FULL OUTER JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         FULL OUTER JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
         FULL OUTER JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
GROUP BY COUNTRY_NAME
ORDER BY COUNT(*) DESC;

SELECT REGION_NAME, COUNT(*)
FROM EMPLOYEES E,
     DEPARTMENTS D,
     LOCATIONS L,
     COUNTRIES C,
     REGIONS R
WHERE (E.DEPARTMENT_ID = D.DEPARTMENT_ID AND C.REGION_ID = R.REGION_ID)
GROUP BY REGION_NAME;







