SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID
FROM EMPLOYEES;

SELECT EMP2.FIRST_NAME manager_name, SUM(EMP2.SALARY), COUNT(*)
FROM EMPLOYEES EMP1
         JOIN EMPLOYEES EMP2 ON (EMP1.MANAGER_ID = EMP2.MANAGER_ID)
GROUP BY EMP2.FIRST_NAME
ORDER BY SUM(EMP2.SALARY) DESC;