SELECT NVL(FIRST_NAME, 'no employee'),
       NVL(LAST_NAME, 'no employee'),
       NVL(SALARY, 0),
       NVL(DEPARTMENT_NAME, 'no department')
FROM EMPLOYEES EM
         FULL OUTER JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);
