SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME, D.MANAGER_ID
FROM EMPLOYEES E
         JOIN DEPARTMENTS D USING (DEPARTMENT_ID);

SELECT *
FROM COUNTRIES;

SELECT *
FROM REGIONS
         JOIN COUNTRIES USING (REGION_ID);

SELECT *
FROM JOB_HISTORY;

SELECT FIRST_NAME, LAST_NAME, JH.JOB_ID, START_DATE, END_DATE
FROM EMPLOYEES
         JOIN JOB_HISTORY JH USING (EMPLOYEE_ID, DEPARTMENT_ID);