SELECT FIRST_NAME, LAST_NAME, EM.JOB_ID, JH.START_DATE, JH.END_DATE
FROM EMPLOYEES EM
         JOIN JOB_HISTORY JH ON (EM.EMPLOYEE_ID = JH.EMPLOYEE_ID);

SELECT *
FROM REGIONS;


SELECT *
FROM DEPARTMENTS DE
         JOIN REGIONS RG ON (
    RG.REGION_ID * 10 = DE.DEPARTMENT_ID
    );


SELECT FIRST_NAME, LAST_NAME, EM.JOB_ID, JH.START_DATE, JH.END_DATE
FROM EMPLOYEES EM
         JOIN JOB_HISTORY JH
              ON (EM.EMPLOYEE_ID = JH.EMPLOYEE_ID OR EM.EMPLOYEE_ID = JH.DEPARTMENT_ID AND SALARY > 10000);

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON EM.DEPARTMENT_ID = DE.MANAGER_ID
