SELECT *
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES EM
         LEFT OUTER JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES EM
         RIGHT OUTER JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);


SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES EM
         FULL OUTER JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);

SELECT POSTAL_CODE, CITY, DEPARTMENT_NAME
FROM LOCATIONS LC
         LEFT OUTER JOIN DEPARTMENTS DE ON (DE.LOCATION_ID = LC.LOCATION_ID);

SELECT DEPARTMENT_NAME, DE.DEPARTMENT_ID
FROM DEPARTMENTS DE
         LEFT OUTER JOIN EMPLOYEES EM ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
WHERE EM.DEPARTMENT_ID IS NULL;