SELECT *
FROM JOBS;

SELECT FIRST_NAME, LAST_NAME, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY * 2 < MAX_SALARY);

SELECT FIRST_NAME, LAST_NAME, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY = MAX_SALARY);

SELECT FIRST_NAME, LAST_NAME, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY < MAX_SALARY);

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES EM
         JOIN JOBS JB ON (EM.JOB_ID = JB.JOB_ID AND SALARY BETWEEN 3000 AND 5000);