SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES EM
         RIGHT OUTER JOIN DEPARTMENTS DE USING (DEPARTMENT_ID);

SELECT *
FROM COUNTRIES;

SELECT *
FROM LOCATIONS;

SELECT COUNTRY_NAME, CITY, STREET_ADDRESS
FROM LOCATIONS LC
         RIGHT OUTER JOIN COUNTRIES CN ON (LC.COUNTRY_ID = CN.COUNTRY_ID);
