SELECT E.SALARY, E.FIRST_NAME
FROM EMPLOYEES E;

SELECT C.COUNTRY_NAME, C.COUNTRY_ID, REGION_ID
FROM REGIONS R
         NATURAL JOIN COUNTRIES C;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME, MANAGER_ID
FROM EMPLOYEES
         NATURAL JOIN DEPARTMENTS;

SELECT *
FROM COUNTRIES;