SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC;

SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.SALARY, DEPARTMENT_NAME
FROM EMPLOYEES E1
         JOIN DEPARTMENTS DE ON (E1.DEPARTMENT_ID = DE.DEPARTMENT_ID)
WHERE SALARY > (SELECT AVG(E2.SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E2.DEPARTMENT_ID)
ORDER BY SALARY DESC;

