SELECT MAX(SALARY)
FROM EMPLOYEES;


SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT MAX(SALARY) / 5
                FROM EMPLOYEES);

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES);

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 180);

SELECT SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 180;

SELECT JOB_TITLE
FROM JOBS JS
         JOIN EMPLOYEES EM ON (JS.JOB_ID = EM.JOB_ID)
HAVING AVG(SALARY) = (SELECT MAX(AVG(SALARY)) FROM EMPLOYEES GROUP BY JOB_ID);


SELECT MAX(AVG(SALARY))
FROM EMPLOYEES
GROUP BY JOB_ID;


