SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES)
ORDER BY SALARY DESC;

SELECT (SELECT MIN(MIN_SALARY) FROM JOBS)              min_zp,
       (SELECT MAX(LENGTH(FIRST_NAME)) FROM EMPLOYEES) samoe_dlinnoe_imya
FROM DUAL;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM EMPLOYEES);


SELECT DEPARTMENT_NAME, MIN(SALARY), MAX(SALARY)
FROM (SELECT SALARY, DEPARTMENT_NAME
      FROM EMPLOYEES EM
               JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID))
GROUP BY DEPARTMENT_NAME;

SELECT SALARY, DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);


SELECT DEPARTMENT_NAME, MIN(SALARY), MAX(SALARY)
FROM (SELECT SALARY, DEPARTMENT_NAME
      FROM EMPLOYEES EM
               JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID))
GROUP BY DEPARTMENT_NAME
HAVING MAX(SALARY) > (SELECT 2 * 5000 FROM DUAL)
   AND MIN(SALARY) < (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 113);









