SELECT *
FROM JOBS;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN (SELECT JOB_ID FROM JOBS WHERE MIN_SALARY > 8000);

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100)

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100);

SELECT DISTINCT DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID);

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES);
