SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.SALARY
FROM EMPLOYEES E1
WHERE SALARY > (SELECT AVG(E2.SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID);

SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE LOCATION_ID IN (
        SELECT LOCATION_ID
        FROM LOCATIONS
        WHERE COUNTRY_ID =
              (SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_NAME = 'Germany')
    )
);

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN (SELECT JOB_ID
                 FROM JOBS
                 WHERE UPPER(JOB_TITLE) LIKE '%MANAGER%'
                   AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES));


SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT MAX(SALARY) FROM EMPLOYEES WHERE FIRST_NAME = 'David');










