SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.SALARY
FROM EMPLOYEES E1
WHERE SALARY > (SELECT AVG(E2.SALARY) FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID);