SELECT DEPARTMENT_NAME, MIN(SALARY), MAX(SALARY)
FROM (SELECT SALARY, DEPARTMENT_NAME
      FROM EMPLOYEES E
               JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID))
GROUP BY DEPARTMENT_NAME
HAVING MAX(SALARY) > (SELECT 2 * 5000 FROM DUAL)
   AND MIN(SALARY) < (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 113);

SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT MAX(SALARY)
                FROM EMPLOYEES) / 5;

SELECT ROUND(AVG(SALARY))
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT ROUND(AVG(SALARY))
                FROM EMPLOYEES);

SELECT FIRST_NAME, SALARY, (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 180)
FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 180);

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 180);