SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT (SELECT MIN(MIN_SALARY) FROM JOBS)              MIN_ZP,
       (SELECT MAX(LENGTH(FIRST_NAME)) FROM EMPLOYEES) SAMOE_DLINNOE_IMYA
FROM DUAL;

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM EMPLOYEES);

SELECT DEPARTMENT_NAME, MIN(SALARY), MAX(SALARY)
FROM (SELECT SALARY, DEPARTMENT_NAME
      FROM EMPLOYEES E
               JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID))
GROUP BY DEPARTMENT_NAME
HAVING MAX(SALARY) > (SELECT 2 * 5000 FROM DUAL)
   AND MIN(SALARY) < (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 113);

SELECT JOB_TITLE, COUNT(*), SUM(SALARY)
FROM JOBS J
         JOIN EMPLOYEES E ON (J.JOB_ID = E.JOB_ID)
-- GROUP BY JOB_TITLE HAVING AVG(SALARY) =
GROUP BY JOB_TITLE
ORDER BY SUM(SALARY) DESC;


SELECT JOB_TITLE
FROM JOBS J
         JOIN EMPLOYEES E ON (J.JOB_ID = E.JOB_ID)
GROUP BY JOB_TITLE
HAVING AVG(SALARY) = (SELECT MAX(AVG(SALARY)) FROM EMPLOYEES GROUP BY JOB_ID);
