SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN
      (SELECT DEPARTMENT_ID
       FROM DEPARTMENTS
       WHERE LOCATION_ID IN (SELECT LOCATION_ID
                             FROM LOCATIONS
                             WHERE COUNTRY_ID = (SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_NAME = 'Germany')));

SELECT *
FROM JOBS;

SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_TITLE, DEPARTMENT_NAME
FROM EMPLOYEES EM
         JOIN JOBS JS ON (EM.JOB_ID = JS.JOB_ID)
         JOIN DEPARTMENTS DE ON (EM.DEPARTMENT_ID = DE.DEPARTMENT_ID)
WHERE JS.JOB_ID IN (SELECT JOB_ID FROM JOBS WHERE UPPER(JOB_TITLE) LIKE '%MANAGER%')
  AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);


SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'David');