SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN
      (SELECT DEPARTMENT_ID
       FROM DEPARTMENTS
       WHERE LOCATION_ID IN (SELECT LOCATION_ID
                             FROM LOCATIONS
                             WHERE COUNTRY_ID = (SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_NAME = 'Germany')));