SELECT *
FROM JOBS
WHERE JOB_ID LIKE '%MAN%'
UNION ALL
SELECT *
FROM JOBS
WHERE JOB_ID LIKE '%MAN%';

SELECT *
FROM JOBS
WHERE JOB_ID LIKE '%MAN%'
UNION
SELECT *
FROM JOBS
WHERE JOB_ID LIKE '%MAN%';

SELECT *
FROM JOBS
WHERE JOB_ID LIKE '%MAN%'
UNION
SELECT *
FROM JOBS
WHERE JOB_ID LIKE '%MAN%';

SELECT JOB_ID, JOB_TITLE, MIN_SALARY
FROM JOBS
WHERE JOB_ID LIKE '%MAN%'
UNION ALL
SELECT JOB_ID, JOB_TITLE, MAX_SALARY
FROM JOBS
WHERE JOB_ID LIKE '%MAN%'
ORDER BY MIN_SALARY;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID > 200
UNION ALL
SELECT JOB_ID, JOB_TITLE, MAX_SALARY
FROM JOBS
WHERE JOB_ID LIKE '%MAN%';

SELECT COUNTRY_ID
FROM COUNTRIES
UNION ALL
SELECT COUNTRY_NAME
FROM COUNTRIES;