SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%'
INTERSECT
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%i%'
MINUS
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%l%';

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%'
UNION
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e%'
INTERSECT
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%l%';

SELECT MANAGER_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20
INTERSECT
SELECT MANAGER_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

SELECT DEPARTMENT_ID DEP, TO_CHAR(NULL), SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
UNION
SELECT TO_NUMBER(NULL), JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;





